### ISSUE TITLE
Create test that demonstrates `BroadcastTx` working.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-db#144]
This is blocking https://github.com/eris-ltd/eris-contracts.js/issues/23, which is important to Casey.

**Comment by silasdavis** [comment]
Wanted to make a quick response, so does this provide what you need:

https://github.com/eris-ltd/eris-db/blob/develop/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/test/client_rpc_test.go#L100

Calls this:

https://github.com/eris-ltd/eris-db/blob/develop/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/test/tests.go#L73

I don't see the relation to the key of Casey's you linked. Could you provide more context for what you are looking for? What seems not to be working currently?

**Comment by NodeGuy** [comment]
Thank you for the quick response.  This appears to be working for permission transactions!  I'm going to keep the issue open as I work on converting more transaction types.

**Comment by benjaminbollen** [comment]
on 1337 the call is routed to https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/transactor.go#L197
```func (this *transactor) TransactAndHold(privKey, address, data []byte, gasLimit, fee int64) (*txs.EventDataCall, error) {```

and on 46657 there is no direct equivalent of `TransactAndHold`, but `BroadcastTxSync`  (or Async) is implemented https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/pipe.go#L460: (edited)

 ```func (pipe *ErisMintPipe) BroadcastTxSync(tx transaction.Tx) (*rpc_tendermint_types.ResultBroadcastTx,
    error) {```

port 1337 does have https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/transactor.go#L123:  
```func (this *transactor) BroadcastTx(tx txs.Tx) (*core_types.Receipt, error) {```

so what we have done is to "move code around" so that double implementations are now right next to eachother and we can communicate more clearly with you (the users) what the api is that we can unify this into

**Comment by NodeGuy** [comment]
This appears to be working now, thank you.
