### ISSUE TITLE
Update dockerfile for armhf according to recent update for normal dockerfile

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#251]
apply https://github.com/eris-ltd/eris-db/pull/250 to dockerfile.armhf

**Comment by silasdavis** [comment]
At time of writing current `Dockerfile` is:

```
FROM quay.io/eris/build
MAINTAINER Monax <support@monax.io>

# Install eris-db, a go app that manages relationships
ENV TARGET eris-db
ENV REPO $GOPATH/src/github.com/eris-ltd/$TARGET

ADD ./glide.yaml $REPO/
ADD ./glide.lock $REPO/
WORKDIR $REPO
RUN glide install

COPY . $REPO/.
RUN cd $REPO/cmd/$TARGET && \
  go build --ldflags '-extldflags "-static"' -o $INSTALL_BASE/$TARGET

# build customizations start here
RUN cd $REPO/client/cmd/eris-client && \
  go build --ldflags '-extldflags "-static"' -o $INSTALL_BASE/eris-client
```

So linked PR would be out-of-date.

@AFDudley arm tag for eris/build image looks out of date. Will you be able to update? https://quay.io/repository/eris/build?tab=tags

If updated, will the Dockerfiles be otherwise identical to above? I think so.

If it is too onerous/we do not plan to keep arm up-to-date I strongly recommend we drop support for ARM rather than maintain out-of-date support.

**Comment by zramsay** [comment]
related to https://github.com/eris-ltd/eris-cli/issues/1088

**Comment by zramsay** [comment]
@silasdavis go ahead and drop IoT support for the time being. I've added this issue to the IoT epic which will be able to be much clean post `0.16.0`

**Comment by zramsay** [comment]
to be dealt with in https://github.com/eris-ltd/eris/issues/1088
