### ISSUE TITLE
use ipfs for state

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#44]

**Comment by benjaminbollen** [comment]
```
// proposal:
// ipfs_db acts as a persistent (levelDB) db that additionally stores
// the values to IPFS, and stores the retrieved IPFS hash for the stored value,
// under the key.
// It is proposed that only the value []byte are stored to IPFS,
// and not the key []byte + value []byte.  The main argument is that the
// key []byte + value IPFS hash, can be separately stored to IPFS; however,
// at the user level the structure of the data might desire a more optimal
// graph structure where the key-value is absorbed into a named link of a
// higher object (commit or transaction block).
```

An initial draft of the proposal is here (wrongly in tendermint/go-db, but it was "easier" or more clear for me to start there).  This is clearly needs to be moved to eris:db/tendermint before any merge, as it intends to depend on eris-ltd/common/go/ipfs, where I will also open a PR.

To invite comments, I already link my first skeleton
https://github.com/tendermint/go-db/compare/master...benjaminbollen:erisdb_issue44_ipfsdb?expand=1

**Comment by benjaminbollen** [comment]
Ethan (964B1493BBE3312278B7DEB 94C39149F7899A345) [6:37 PM] 
the better thing, and maybe actually simpler, then, is to use ipfs instead of the merkle tree
[...]
Ethan (964B1493BBE3312278B7DEB 94C39149F7899A345) [6:45 PM] 
or, maybe find a way to parameterize the hash function in go-merkle, so we can pass in what we want from above, eg. ripemd160 or sha3 or ipfs itself
[...]
Ethan (964B1493BBE3312278B7DEB 94C39149F7899A345) [6:52 PM] 
sounds good. ya i think using it for the hashes in go-merkle instead of ripemd160 will work nicely

**Comment by compleatang** [comment]
will revisit this later.
