### ISSUE TITLE
reconcile eris-db rpc port with tendermint rpc port

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#71]
this is blocking until we move to tmsp (post 0.12.0). until we formally move to tmsp this work isn't very important. after that switch, we will need to control "more" from the erisdb-rpc port. Indeed, erisdb-rpc port should be the single gateway to `eris chains` and then be able to proxy to tmint's rpc if needed (or the application manager, etc.)

**Comment by compleatang** [comment]
what is currently in erisdb is likely to become the base for our `messenger` component of `eris chains` ...

**Comment by ebuchman** [comment]
right. so this is a big one. we need to strategize a bit about what httpserver/rpc framework we want to use here. I like tendermint/go-rpc because it exposes the same endpoints as GET requests (so we can see in browser), as jsonrpc POST, and as websocket messages. of course the js libs use the erisdb "rest" api but I believe there have been some issues there and dave has even started using the 46657 api.  granted there's no rush on this but maybe we should put @NodeGuy in charge of this interface since he's responsible for the js tools which will be talking to it, and we can make the mint-client tools conform to whatever he thinks is best for the API here.

**Comment by compleatang** [comment]
It's bigger than the js tooling. We will discuss this at the chains team summit next week.

**Comment by compleatang** [comment]
overly broad. closing
