### ISSUE TITLE
erisdb itself should respect the eris platform logging standards

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#78]

**Comment by compleatang** [comment]
moving to 0.12.1|0.16.0 so that we have time to appropriately look at this issue.

**Comment by silasdavis** [comment]
I am tentatively closing this because I think with keys and cm coming under eris-db some of this is subsumed. Also I am not clear what the eris platform logging standards are, and discussions has arrived at the idea that CLI tooling does not need to have identical style logging to eris-db. I think the 'spirit' in which the issue was created has better expression in the parent Epic and its children.
